[package]
name = "preprocess"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.99"
flate2 = "1.0"
loro = "0.16.12"
anyhow = "1.0.89"
